services:
  - type: web
    name: flask-web
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: REDIS_URL
        value: redis://red-d0r56hre5dus73fkg89g:6379
    disk:
      name: data-disk
      mountPath: /data

  - type: worker
    name: celery-worker
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: celery -A celery_worker.celery worker --loglevel=info --concurrency=1
    envVars:
      - key: FLASK_ENV
        value: production
      - key: REDIS_URL
        value: redis://red-d0r56hre5dus73fkg89g:6379
    disk:
      name: data-disk
      mountPath: /data